# Generated by Django 5.1 on 2024-09-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('11s', '11s'), ('7s', '7s'), ('5s', '5s'), ('Cricket', 'Cricket'), ('Tennis', 'Tennis'), ('Basketball', 'Basketball'), ('TableTennis', 'TableTennis'), ('Volleyball', 'Volleyball'), ('Badminton', 'Badminton'), ('Swimming Pool', 'Swimming Pool')], max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logo')),
                ('turf_image_1', models.ImageField(upload_to='turfimages')),
                ('turf_image_2', models.ImageField(upload_to='turfimages')),
                ('turf_images_3', models.ImageField(upload_to='turfimages')),
                ('is_locker', models.BooleanField(default=False)),
                ('is_parking', models.BooleanField(default=False)),
                ('is_cctv', models.BooleanField(default=False)),
                ('is_washroom', models.BooleanField(default=False)),
                ('is_dressingroom', models.BooleanField(default=False)),
                ('is_purifiedwater', models.BooleanField(default=False)),
                ('is_firstaidkit', models.BooleanField(default=False)),
                ('price', models.ManyToManyField(to='exalts.rate')),
            ],
        ),
    ]
